USE Adg;

INSERT INTO FAQ(question,answer) VALUES('What do I need to be admitted to LFC University?','Admission requirements for our undergraduate programs are available on the LFC website.');
INSERT INTO FAQ(question,answer) VALUES('What should I do after I submit my application?','Please check your email and application status regularly. LFC will send you important updates when needed.');
INSERT INTO FAQ(question,answer) VALUES('What is the difference between required and recommended documents?','UBC must receive your required documents before we can evaluate your application. Recommended documents are not needed for your admission evaluation but they help determine whether you meet specific course pre-requisites or degree requirements.');
INSERT INTO FAQ(question,answer) VALUES('Can I change my personal profile after I submit it?','No, once you have submitted your Personal Profile, it cannot be changed or amended. Please review your responses carefully before submitting. However, you are able to change password and related contact information later on.');
INSERT INTO FAQ(question,answer) VALUES('What are your language requirements?','TOEFL (Test of English as a Foreign Language): we require a minimum score of 100 (internet-based).');
INSERT INTO FAQ(question,answer) VALUES('What is your deadline for admission?','Applications for January 2014 will be accepted from February 1st to June 14, 2013.');
INSERT INTO FAQ(question,answer) VALUES('Where can I get information about your program?','The Master of Software Systems website contains all the information needed for applying to our program. ');
INSERT INTO FAQ(question,answer) VALUES('How do I apply/find admissions information?','If you are a prospective undergraduate, the LFC University website provides comprehensive information on applying for admission to LFC.');
INSERT INTO FAQ(question,answer) VALUES('What Information is Available on Financial Assistance?','Student Services provides information about awards and financial aid.');
INSERT INTO FAQ(question,answer) VALUES('Is There Any Information for International Students?','International Student Services provides information and support for international students.');
INSERT INTO FAQ(question,answer) VALUES('Is There an Online Academic Calendar with Course and Requirement Information? ',' The Academic Calendar contains information on courses offered by LFC, and their requirements and prerequisites. The Calendar can be found on the Student Services website, where you can also find a listing of offered courses.');
INSERT INTO FAQ(question,answer) VALUES('How Do I Find Out About Lifelong & Distance Learning Opportunities and Professional Programs?','See Continuing & Distance Education for a listing of alternative learning options available at LFC.');
INSERT INTO FAQ(question,answer) VALUES('What is a Message Centre?','The message centre is for receiving notifications from RED system.');
INSERT INTO FAQ(question,answer) VALUES('Where can I get technical support on your system?','Please read the user manual of the RED enrolment system or you can directly contact the system administrator. ');
INSERT INTO FAQ(question,answer) VALUES('Can I change my password?','Yes, please log into the RED system and go to Personal Info page, the change password functionality is provided there.')